/* ============================================================
   Switzerland 2026 — public itinerary data (no personal info).
   Registered on window.TRIPS so the hub can list it.
   Full private version (prices, confirmations, booking refs) is
   kept out of this repo in data.private.js.
   ============================================================ */
window.TRIPS = window.TRIPS || {};
window.TRIPS.switzerland = {
  meta: {
    id: "switzerland",
    emoji: "🇨🇭",
    country: "Switzerland",
    title: "Switzerland 2026",
    subtitle: "9-day self-drive itinerary",
    startDate: "2026-06-13",
    endDate: "2026-06-21",
    chfToSgd: 1.63,
    currency: "CHF",
    note: "9 days by car through Zurich, the Bernese Oberland and Lake Geneva — mountains, lakes, waterfalls, cheese and chocolate.",
  },

  /* representative coordinates per weather region (for forecasts) */
  regions: {
    north:    { label: "Zurich & Lucerne", lat: 47.05, lng: 8.31 },
    oberland: { label: "Bernese Oberland", lat: 46.66, lng: 7.86 },
    leman:    { label: "Lake Geneva",      lat: 46.43, lng: 6.91 },
  },

  flights: [
    { code: "SQ346", route: "Singapore → Zurich", date: "2026-06-13",
      dep: "Sat 13 Jun 01:25 (SIN)", arr: "Sat 13 Jun 08:15 (ZRH)" },
    { code: "SQ345", route: "Zurich → Singapore", date: "2026-06-21",
      dep: "Sun 21 Jun 11:45 (ZRH)", arr: "Mon 22 Jun 05:55 (SIN)" },
  ],

  car: {
    company: "Rental car",
    pickup: "Zurich Main Railway · Sun 14 Jun 08:00",
    returns: [{ who: "Drop-off", value: "Zurich Main Station · Sat 20 Jun 18:00" }],
  },

  /* ---- Hotels (public details only) ---- */
  hotels: [
    { name: "EMA House Hotel Suites", location: "Zurich", nights: 1, night: "13 Jun",
      url: "https://ema-house.ch/en/", room: "Junior Suite",
      phone: "+41 44 368 36 68", addr: "Nordstrasse 1, 8006 Zürich" },
    { name: "Hotel Continental Park Luzern", location: "Lucerne", nights: 1, night: "14 Jun",
      url: "https://www.continental.ch/en/rooms-and-suites/rooms/", room: "Family suite / twin",
      phone: "+41 41 228 90 50", addr: "Murbacherstrasse 4, 6002 Luzern" },
    { name: "Hotel Gletschergarten", location: "Grindelwald", nights: 1, night: "15 Jun",
      url: "https://hotel-gletschergarten.ch/en/home/", room: "Double Standard (rustic)",
      phone: "+41 33 853 17 21", addr: "Obere Gletscherstrasse 1, 3818 Grindelwald" },
    { name: "Stella Hotel", location: "Interlaken", nights: 1, night: "16 Jun",
      url: "https://www.stella-hotel.ch/en/interlaken-hotel/", room: "Large / Quadruple Room",
      phone: "+41 33 822 88 71", addr: "General-Guisan-Strasse 2, 3800 Interlaken" },
    { name: "Modern Times Hotel", location: "Vevey / Montreux", nights: 1, night: "17 Jun",
      url: "https://www.moderntimeshotel.ch/", room: "King + Spacious Room",
      phone: "+41 21 925 22 22", addr: "Chemin du Genévrier 20, 1806 St-Légier-La Chiésaz" },
    { name: "Rotary Hotel Geneva (MGallery)", location: "Geneva", nights: 2, night: "18–19 Jun",
      url: "https://mgallery.accor.com/", room: "Classic Room",
      phone: "+41 22 908 80 80", addr: "18-20 Rue du Cendrier, 1201 Genève" },
    { name: "Hotel Adler", location: "Zurich", nights: 1, night: "20 Jun",
      url: "https://hotel-adler.ch/en/", room: "Family Room (departure night)",
      phone: "+41 44 266 96 96", addr: "Rosengasse 10, 8001 Zürich" },
  ],

  /* ---- Day-by-day schedule ---- */
  days: [
    {
      n: 1, date: "2026-06-13", dow: "Sat", title: "Arrive Zurich", region: "north",
      route: "Singapore ✈ Zurich · explore the city",
      hotel: "EMA House Hotel Suites (Zurich)",
      drones: ["Lindenhof Hill", "Quaibrücke / Lake Zurich from Bürkliplatz"],
      segments: [
        { t: "08:15", type: "flight", act: "Arrive Zurich on SQ346", note: "Dep SIN 13 Jun 01:25, arr ZRH 08:15" },
        { t: "09:15", type: "drive", act: "Private car: airport → hotel", note: "~12 km, 30 min" },
        { t: "09:45", type: "hotel", act: "Check in at EMA House" },
        { t: "10:15", type: "shop", act: "Watch shopping on Bahnhofstrasse", note: "Patek Philippe (Bahnhofstrasse 31), Bucherer Flagship (Bahnhofstrasse 50). Photos at Paradeplatz." },
        { t: "12:15", type: "meal", act: "Lunch (play by ear)", note: "Zeughauskeller or zum Kropf — rösti, Geschnetzeltes" },
        { t: "13:30", type: "walk", act: "Zurich Old Town (Altstadt)", note: "Augustinergasse, Grossmünster & Fraumünster. Lindenhof Hill (best early). Treats at Läderach / Sprüngli." },
        { t: "15:30", type: "walk", act: "Lake Zurich promenade", note: "Bürkliplatz toward Arboretum Zurich" },
        { t: "17:00", type: "free", act: "Free & easy", note: "Lindt Home of Chocolate (~15 min away)" },
        { t: "18:30", type: "meal", act: "Dinner: Zeughauskeller", note: "Bahnhofstrasse 28, Beim Paradeplatz, 8001 Zürich" },
        { t: "20:00", type: "hotel", act: "Back to hotel" },
      ],
    },
    {
      n: 2, date: "2026-06-14", dow: "Sun", title: "Zurich → Stoos → Lucerne", region: "north",
      route: "Pick up car · Fronalpstock · Lucerne old town",
      hotel: "Hotel Continental Park Luzern",
      drones: [],
      segments: [
        { t: "07:00", type: "meal", act: "Breakfast: Café Oscar at the station (takeaway)", note: "Sun opens 06:00" },
        { t: "08:00", type: "car", act: "Pick up rental car — Zurich Main Railway", note: "08:00" },
        { t: "08:30", type: "drive", act: "Drive Zurich → Schwyz Stoosbahn", note: "65 km / 1 h" },
        { t: "09:30", type: "cable", act: "Funicular + chairlift to Fronalpstock" },
        { t: "10:00", type: "walk", act: "Panorama Walk (1.5 km)" },
        { t: "11:30", type: "cable", act: "Funicular + chairlift back to Stoos" },
        { t: "12:00", type: "drive", act: "Drive to Lucerne town", note: "50 km / 1 h" },
        { t: "13:00", type: "meal", act: "Lunch (play by ear)" },
        { t: "14:30", type: "walk", act: "Chapel Bridge, Lion Monument, Old Town", note: "Shopping at Schwanenplatz (Bucherer, Max Chocolatier)" },
        { t: "17:00", type: "drive", act: "Drive to Meggenhorn Castle", note: "8 km / 20 min" },
        { t: "17:20", type: "sight", act: "Meggenhorn Castle", note: "Free admission to grounds; castle interior Sunday afternoon only" },
        { t: "18:05", type: "drive", act: "Drive back to Lucerne hotel", note: "8 km / 20 min" },
        { t: "18:25", type: "hotel", act: "Check in at Continental Park Luzern" },
        { t: "19:00", type: "meal", act: "Dinner: Rathaus Brauerei", note: "Unter der Egg 2, 6004 Luzern · indoor seats only" },
      ],
    },
    {
      n: 3, date: "2026-06-15", dow: "Mon", title: "Lucerne → Grindelwald", region: "oberland",
      route: "Lakes, drone stops & waterfalls",
      hotel: "Hotel Gletschergarten (Grindelwald)",
      drones: ["Lake Lungern viewpoint", "Iseltwald Pier (Crash Landing on You)", "Outside Lauterbrunnen village", "Staubbach Falls"],
      segments: [
        { t: "07:00", type: "meal", act: "Breakfast in hotel or Confiserie Bachmann, Bahnhof Luzern", note: "Mon opens 06:15 — get schoggibrötli (chocolate bread roll)" },
        { t: "08:00", type: "drive", act: "Drive Luzern → Lake Lungern viewpoint", note: "Aussichtspunkt Chalrutirank · 40 km / 45 min" },
        { t: "08:45", type: "drone", act: "Drone + photos over Lungernsee" },
        { t: "09:15", type: "drive", act: "Drive to Iseltwald Pier (Lake Brienz)", note: "‘Crash Landing on You’ filming location · 40 km / 40 min" },
        { t: "09:55", type: "drone", act: "Drone/photos at Iseltwald Pier + gelato break" },
        { t: "10:40", type: "drive", act: "Drive to Harder Kulm", note: "20 km / 20 min" },
        { t: "11:00", type: "cable", act: "Funicular up Harder Kulm", note: "From Interlaken OST (10 min walk). 3 adults + 3 children." },
        { t: "11:30", type: "meal", act: "Lunch: Harder Kulm Panoramic Restaurant", note: "No booking needed (reservations only for 8+ pax)" },
        { t: "12:30", type: "walk", act: "Two Lakes Bridge (Zwei-Seen-Steg) viewing platform" },
        { t: "13:00", type: "cable", act: "Funicular down + walk to car" },
        { t: "13:30", type: "drive", act: "Drive to Sigriswil Panoramic Bridge", note: "20 km / 40 min" },
        { t: "14:15", type: "sight", act: "Cross the Sigriswil bridge + photos", note: "CHF 8/person, no booking" },
        { t: "14:45", type: "drive", act: "Drive to Staubbach Falls", note: "30 km / 45 min" },
        { t: "15:30", type: "sight", act: "Staubbach Falls (walk behind the waterfall)", note: "Free of charge" },
        { t: "16:15", type: "drive", act: "Drive to Trümmelbach Falls", note: "5 km / 5 min" },
        { t: "16:30", type: "sight", act: "Trümmelbach Falls", note: "Bring rain jacket, dry change of clothes, waterproof phone case. CHF 16 / CHF 7, buy on site." },
        { t: "17:45", type: "drive", act: "Drive to Grindelwald", note: "20 km / 40 min" },
        { t: "18:30", type: "hotel", act: "Check in at Grindelwald hotel, change" },
        { t: "19:00", type: "meal", act: "Dinner: The Glacier", note: "55 Endweg, Grindelwald" },
      ],
    },
    {
      n: 4, date: "2026-06-16", dow: "Tue", title: "Grindelwald First → Interlaken", region: "oberland",
      route: "Adventure peak + glacier canyon",
      hotel: "Stella Hotel (Interlaken)",
      drones: ["Lake Bachalpsee", "Terrassenweg"],
      segments: [
        { t: "07:00", type: "meal", act: "Breakfast in Grindelwald hotel (included)" },
        { t: "07:45", type: "walk", act: "Walk to Firstbahn station", note: "8 min, 500 m" },
        { t: "08:00", type: "cable", act: "Gondola up to Grindelwald First + Cliff Walk", note: "Pre-booked (gondola + Cliff Walk); First opens 08:00." },
        { t: "09:00", type: "walk", act: "Return hike to Lake Bachalpsee", note: "6 km / ~2 h — morning is best; bring snacks." },
        { t: "11:30", type: "play", act: "First View platform, First Flyer, First Glider, Mountain Cart, Trottibike", note: "Attraction tickets on the spot." },
        { t: "13:00", type: "cable", act: "Gondola down + walk to car" },
        { t: "13:45", type: "free", act: "Tea / rest (play by ear) in Grindelwald" },
        { t: "14:15", type: "drive", act: "Drive to Glacier Canyon", note: "5 km / 10 min" },
        { t: "14:30", type: "sight", act: "Glacier Canyon (Gletscherschlucht)" },
        { t: "16:30", type: "walk", act: "Terrassenweg walk + Café 3692 (early bite)" },
        { t: "17:30", type: "drive", act: "Drive to Interlaken hotel", note: "22 km / 30 min" },
        { t: "18:00", type: "meal", act: "Dinner in Interlaken (play by ear)", note: "Per Bacco, Hoppla Bistro, Taverne Interlaken, Fondue Villa, Rst Tenne" },
        { t: "19:30", type: "hotel", act: "Check in at Stella Hotel" },
      ],
    },
    {
      n: 5, date: "2026-06-17", dow: "Wed", title: "Interlaken → Gruyères → Vevey", region: "leman",
      route: "Cheese, chocolate & a medieval village",
      hotel: "Modern Times Hotel (Vevey)",
      drones: ["Jaunpass", "Lavaux Vineyards"],
      segments: [
        { t: "08:00", type: "meal", act: "Breakfast in Interlaken hotel (included)" },
        { t: "09:00", type: "drive", act: "Drive Interlaken → Jaunpass 1676 viewpoint", note: "via Route 11 · 55 km / 60 min" },
        { t: "10:15", type: "drone", act: "Photo / drone stop at Jaunpass" },
        { t: "10:30", type: "drive", act: "Drive to Gruyères", note: "30 km / 45 min" },
        { t: "11:30", type: "sight", act: "Maison Cailler Chocolate Factory", note: "Pre-booked timed entry ~11:30/11:45 — be on site 15 min early. 3 adults + 3 children." },
        { t: "13:30", type: "drive", act: "Drive chocolate factory → Gruyères village", note: "10 km / 15 min" },
        { t: "13:45", type: "meal", act: "Lunch (play by ear)", note: "Le Chalet de Gruyères or the cheese factory restaurant" },
        { t: "14:45", type: "sight", act: "Maison du Gruyère cheese factory", note: "Tickets on the spot; cheese-making demo runs through the day. ~15 min walk from car park." },
        { t: "16:00", type: "sight", act: "Château de Gruyères", note: "Open 09:00–18:00. Combined ticket with cheese / HR Giger available." },
        { t: "17:15", type: "sight", act: "HR Giger Museum (optional)", note: "Between the château and the car park · 10:00–18:00." },
        { t: "17:30", type: "drive", act: "Drive Gruyères → Vevey", note: "40 km / 35 min" },
        { t: "18:15", type: "hotel", act: "Check in at Vevey hotel, rest" },
        { t: "19:15", type: "drive", act: "Drive to dinner", note: "4.5 km / 6 min" },
        { t: "19:30", type: "meal", act: "Dinner: Là-Haut", note: "21 Village Street, 1803 Chardonne" },
        { t: "21:00", type: "drive", act: "Drive back to hotel" },
      ],
    },
    {
      n: 6, date: "2026-06-18", dow: "Thu", title: "Montreux · Lavaux · Lausanne → Geneva", region: "leman",
      route: "Castle, vineyards & the Olympic Museum",
      hotel: "Rotary Hotel Geneva",
      drones: ["Lavaux Vineyards", "Chillon Castle", "Ouchy Promenade"],
      segments: [
        { t: "07:45", type: "drive", act: "Drive Vevey → Montreux", note: "7 km / 15 min" },
        { t: "08:00", type: "meal", act: "Breakfast in Montreux", note: "Tea Room de la Baye, 23 Rue du Pont — Thu opens 8am" },
        { t: "08:30", type: "walk", act: "Promenade walk to Freddie Mercury statue" },
        { t: "09:15", type: "sight", act: "Queen Studio Experience (free)", note: "Inside Casino Barrière" },
        { t: "10:00", type: "shop", act: "Marché Couvert (covered market) + small shops/café" },
        { t: "10:45", type: "drive", act: "Drive to Chillon Castle", note: "3 km / 5 min" },
        { t: "10:55", type: "sight", act: "Château de Chillon" },
        { t: "12:30", type: "meal", act: "Lunch: La Rouvenaz", note: "Rue du Marché 1, 1820 Montreux" },
        { t: "13:30", type: "drive", act: "Drive to Lausanne Olympic Museum", note: "28 km / 32 min" },
        { t: "14:15", type: "sight", act: "Olympic Museum", note: "Open Tue-Sun 9-18. ~1.5-2 h." },
        { t: "15:15", type: "drive", act: "Drive to Ouchy Promenade" },
        { t: "15:30", type: "drone", act: "Ouchy Promenade + fly drones" },
        { t: "16:30", type: "drive", act: "Drive Ouchy → Geneva hotel", note: "65 km / 65 min" },
        { t: "18:00", type: "hotel", act: "Check in at Geneva hotel / explore" },
        { t: "19:15", type: "meal", act: "Dinner: Les Armures", note: "Rue du Soleil-Levant, 1204 Genève" },
      ],
    },
    {
      n: 7, date: "2026-06-19", dow: "Fri", title: "Full day in Geneva", region: "leman",
      route: "Lake & Jet d'Eau · Old Town · Patek Philippe",
      hotel: "Rotary Hotel Geneva",
      drones: ["Mont Salève viewpoint (in France, short drive)", "Parc Moynier / Parc de la Perle (Jet d'Eau view)"],
      segments: [
        { t: "08:00", type: "meal", act: "Breakfast in Geneva hotel (included)" },
        { t: "09:00", type: "walk", act: "Jardin Anglais (Flower Clock), Lake Geneva & Jet d'Eau", note: "Halle de Rive food stalls nearby for a snack/lunch." },
        { t: "11:30", type: "walk", act: "Old Town (Vieille Ville)", note: "St-Pierre Cathedral tower, Maison Tavel, Place du Bourg-de-Four, Treille Promenade (longest bench), Reformation Wall, Parc des Bastions." },
        { t: "14:00", type: "sight", act: "Patek Philippe Museum", note: "Open 14:00–18:00 · same-day tickets · A CHF 10, U18 free." },
        { t: "16:00", type: "shop", act: "Rue du Rhône shopping & Bon Génie", note: "Then Place des Nations (UN, Broken Chair) and Rue du Mont-Blanc." },
        { t: "17:00", type: "free", act: "Rest at hotel" },
        { t: "19:00", type: "meal", act: "Dinner: Arakel", note: "5-course · Rue Henri-Blanvalet 17, 1207 Genève" },
      ],
    },
    {
      n: 8, date: "2026-06-20", dow: "Sat", title: "Geneva → House of Läderach → Zurich", region: "north",
      route: "Drive east · chocolate · Zurich",
      hotel: "Hotel Adler (Zurich)",
      drones: [],
      segments: [
        { t: "07:00", type: "meal", act: "Breakfast in Geneva hotel (included)" },
        { t: "08:30", type: "drive", act: "Drive Geneva → Bilten / Schänis", note: "333 km / ~3 h 50 min (alt. via Zurich ≈ 300 km / 3 h)" },
        { t: "12:45", type: "free", act: "Buffer / rest / lunch on arrival" },
        { t: "13:00", type: "sight", act: "House of Läderach — chocolate museum + atelier", note: "Grabenstrasse 6, 8865 Bilten. Pre-booked timed entry ~13:00 · museum + walk-in atelier ~45 min." },
        { t: "14:15", type: "drive", act: "Drive Bilten → Zurich", note: "55 km / 50 min" },
        { t: "15:05", type: "hotel", act: "Drop bags at Hotel Adler, Zurich", note: "Rosengasse 10, 8001 Zürich (unloading only)" },
        { t: "18:00", type: "car", act: "Return rental car — Zurich Main Station", note: "~5 min drive from the hotel" },
      ],
    },
    {
      n: 9, date: "2026-06-21", dow: "Sun", title: "Departure — fly home from Zurich", region: "north",
      route: "Zurich · fly home",
      hotel: "Return flight",
      drones: [],
      segments: [
        { t: "08:00", type: "meal", act: "Breakfast / last-minute Zurich stroll" },
        { t: "09:00", type: "drive", act: "Travel to Zurich Airport" },
        { t: "11:45", type: "flight", act: "SQ345 Zurich → Singapore", note: "Dep 21 Jun 11:45 (ZRH), arr 22 Jun 05:55 (SIN)" },
      ],
    },
  ],

  /* ---- Restaurants (names + public addresses only) ---- */
  restaurants: [
    { name: "Zeughauskeller", day: "Sat 13 Jun", time: "18:30", addr: "Bahnhofstrasse 28, 8001 Zürich" },
    { name: "Rathaus Brauerei", day: "Sun 14 Jun", time: "19:00", addr: "Unter der Egg 2, 6004 Luzern" },
    { name: "The Glacier", day: "Mon 15 Jun", time: "19:00", addr: "55 Endweg, Grindelwald" },
    { name: "Interlaken (play by ear)", day: "Tue 16 Jun", time: "18:40", addr: "Taverne Interlaken / Per Bacco / Hoppla" },
    { name: "Là-Haut", day: "Wed 17 Jun", time: "19:30", addr: "21 Village St, 1803 Chardonne" },
    { name: "La Rouvenaz (lunch)", day: "Thu 18 Jun", time: "12:30", addr: "Rue du Marché 1, 1820 Montreux" },
    { name: "Les Armures", day: "Thu 18 Jun", time: "19:15", addr: "Rue du Soleil-Levant, 1204 Genève" },
    { name: "Arakel", day: "Fri 19 Jun", time: "19:00", addr: "Rue Henri-Blanvalet 17, 1207 Genève" },
  ],

  /* ---- Map: key stops with coordinates ---- */
  places: [
    { name: "Paradeplatz / Bahnhofstrasse", day: 1, lat: 47.3699, lng: 8.5390 },
    { name: "Lindenhof Hill (drone)", day: 1, lat: 47.3731, lng: 8.5410 },
    { name: "Grossmünster", day: 1, lat: 47.3701, lng: 8.5442 },
    { name: "Fraumünster", day: 1, lat: 47.3699, lng: 8.5414 },
    { name: "Lake Zurich (Bürkliplatz)", day: 1, lat: 47.3664, lng: 8.5409 },
    { name: "Lindt Home of Chocolate", day: 1, lat: 47.3216, lng: 8.5470 },
    { name: "Stoosbahn (funicular base)", day: 2, lat: 46.9929, lng: 8.6577 },
    { name: "Fronalpstock / Stoos", day: 2, lat: 46.9776, lng: 8.6650 },
    { name: "Chapel Bridge, Lucerne", day: 2, lat: 47.0517, lng: 8.3076 },
    { name: "Lion Monument, Lucerne", day: 2, lat: 47.0585, lng: 8.3112 },
    { name: "Schwanenplatz (shopping)", day: 2, lat: 47.0527, lng: 8.3093 },
    { name: "Meggenhorn Castle", day: 2, lat: 47.0556, lng: 8.3889 },
    { name: "Lake Lungern viewpoint", day: 3, lat: 46.7869, lng: 8.1597 },
    { name: "Iseltwald Pier (CLOY)", day: 3, lat: 46.6897, lng: 7.9560 },
    { name: "Harder Kulm", day: 3, lat: 46.6936, lng: 7.8520 },
    { name: "Sigriswil Panoramic Bridge", day: 3, lat: 46.7136, lng: 7.7060 },
    { name: "Staubbach Falls", day: 3, lat: 46.5928, lng: 7.9090 },
    { name: "Trümmelbach Falls", day: 3, lat: 46.5783, lng: 7.9080 },
    { name: "Grindelwald First", day: 4, lat: 46.6593, lng: 8.0540 },
    { name: "Lake Bachalpsee", day: 4, lat: 46.6655, lng: 8.0290 },
    { name: "Glacier Canyon (Gletscherschlucht)", day: 4, lat: 46.6210, lng: 8.0440 },
    { name: "Jaunpass", day: 5, lat: 46.6203, lng: 7.3370 },
    { name: "Château de Gruyères", day: 5, lat: 46.5847, lng: 7.0820 },
    { name: "Maison du Gruyère", day: 5, lat: 46.5862, lng: 7.0705 },
    { name: "HR Giger Museum", day: 5, lat: 46.5843, lng: 7.0823 },
    { name: "Maison Cailler (Broc)", day: 5, lat: 46.6178, lng: 7.0610 },
    { name: "Château de Chillon", day: 6, lat: 46.4142, lng: 6.9276 },
    { name: "Queen Studio Experience (Casino Barrière)", day: 6, lat: 46.4358, lng: 6.9128 },
    { name: "Marché Couvert, Montreux", day: 6, lat: 46.4345, lng: 6.9106 },
    { name: "Freddie Mercury statue, Montreux", day: 6, lat: 46.4316, lng: 6.9110 },
    { name: "Olympic Museum, Lausanne", day: 6, lat: 46.5089, lng: 6.6340 },
    { name: "Ouchy Promenade", day: 6, lat: 46.5070, lng: 6.6260 },
    { name: "Jet d'Eau", day: 7, lat: 46.2074, lng: 6.1557 },
    { name: "Jardin Anglais (Flower Clock)", day: 7, lat: 46.2044, lng: 6.1503 },
    { name: "Place du Bourg-de-Four", day: 7, lat: 46.2009, lng: 6.1492 },
    { name: "St-Pierre Cathedral, Geneva", day: 7, lat: 46.2010, lng: 6.1483 },
    { name: "Patek Philippe Museum", day: 7, lat: 46.1974, lng: 6.1430 },
    { name: "Rue du Rhône (shopping)", day: 7, lat: 46.2040, lng: 6.1480 },
    { name: "Place des Nations (UN)", day: 7, lat: 46.2226, lng: 6.1399 },
    { name: "Parc des Bastions", day: 7, lat: 46.1985, lng: 6.1460 },
    { name: "House of Läderach (Bilten)", day: 8, lat: 47.1110, lng: 9.0170 },
  ],

  /* ---- Typical June weather (fallback when live forecast is unavailable) ---- */
  weather: [
    { region: "Zurich & Lucerne (lowlands)", hi: "22°C", lo: "12°C", note: "Mild; mix of sun and showers, occasional afternoon thunderstorm." },
    { region: "Bernese Oberland — Grindelwald, Interlaken", hi: "20°C", lo: "9°C", note: "Cooler in the valleys; mountain tops (First, Fronalpstock) can be near freezing — bring layers. Afternoon storms common." },
    { region: "Lake Geneva — Gruyères, Montreux, Lausanne, Geneva", hi: "23°C", lo: "13°C", note: "Warmest region, often sunny; cooler lake breeze in the evening." },
  ],

  phrasebook: {
    de: {
      label: "German — Zurich, Lucerne, Grindelwald, Interlaken",
      rows: [
        ["Hello", "Grüezi"], ["Thank you", "Danke"], ["Please", "Bitte"],
        ["Excuse me", "Entschuldigung"], ["Do you speak English?", "Sprechen Sie Englisch?"],
        ["How much is it?", "Wie viel kostet das?"], ["The bill, please", "Die Rechnung, bitte"],
        ["Water", "Wasser"], ["Help!", "Hilfe!"], ["Goodbye", "Uf Wiederluege"],
      ],
    },
    fr: {
      label: "French — Gruyères, Montreux, Lausanne, Geneva",
      rows: [
        ["Hello", "Bonjour"], ["Thank you", "Merci"], ["Please", "S'il vous plaît"],
        ["Excuse me", "Excusez-moi"], ["Do you speak English?", "Parlez-vous anglais ?"],
        ["How much is it?", "C'est combien ?"], ["The bill, please", "L'addition, s'il vous plaît"],
        ["Water", "De l'eau"], ["Help!", "Au secours !"], ["Goodbye", "Au revoir"],
      ],
    },
  },

  practical: {
    emergency: [
      { label: "Europe-wide emergency", value: "112" },
      { label: "Police", value: "117" },
      { label: "Ambulance", value: "144" },
      { label: "Fire", value: "118" },
    ],
    packing: [
      "Rain jacket (Trümmelbach Falls)",
      "Waterproof phone case (Trümmelbach Falls)",
      "Dry change of clothes (Trümmelbach Falls)",
      "Drone + spare batteries + SD cards",
      "Passports + driving licence (rental car)",
      "EU / Swiss Type-J power adapter",
      "Warm layer for mountain tops (Fronalpstock, First)",
      "Comfortable walking shoes",
      "Sunglasses + sunscreen",
    ],
    droneNote: "Switzerland follows EU drone rules — register, label your drone, keep line of sight, and avoid airports, crowds and nature reserves. Check local restrictions before each flight.",
  },
};
